### PR TITLE
make scanners configurable

### PR DESCRIPTION
**Pull request by glanotte**
This is just a spike to see if this is the track you want to take, if you like it I will add some specs. If not, let me know what you think might be more inline with your methodology. 

Thanks for assist!

references #55

### CODE REVIEW

**Comment by rubysolo** [comment]
This looks like a good initial direction.  What about making `available_scanners` a method instead of a constant?

**Comment by glanotte** [comment]
good call, that is a bit cleaner

**Comment by glanotte** [comment]
@rubysolo what do you think?

**Comment by rubysolo** [comment]
Great, thanks!

**Pull request closed without merging**
