### PR TITLE
Add case statement

### PR DESCRIPTION
**Pull request by tristil**
As discussed here https://github.com/rubysolo/dentaku/issues/60

```
Missing from this implementation:

- support for nested case statements (see pending spec)
- else keyword
- non-equality comparisons (greater than, less than)
```

There are probably many things that need to be changed here. I sort of can't believe that the parsing algorithm works (but it does for the cases I tested) and welcome any suggestions on how to clean it up or better reveal intention. I would also be willing to refactor out an object that only handles the case parsing and that calls into the main parser loop somehow (in an add-on commit).

I will keep working on the issue with nested case statements (I left a pending spec in the main commit) and aim to include this in an add-on commit. Likewise I will work on an ELSE keyword, although I think this can wait for a follow-up PR.

I don't mind dropping the commit with the development dependencies, although I find these very useful.

### CODE REVIEW

**Comment by rubysolo** [comment]
Nice -- this looks good!  I would like to drop the dev dependencies or find a way to make them load conditionally, since they are the only thing that break the travis build for 1.9.3 and Rubinius.  Thank you for working on this!

**Comment by tristil** [comment]
@rubysolo I found a way to conditionally load those gems just for MRI 2.x+ and Travis passes now. If you don't like it I'm happy to drop it. On the other hand if you don't mind the approach it would be nice to have these in because I plan to do some more development and I use these all the time :)

**Comment by rubysolo** [comment]
Okay, this approach can work.  Let me know if you have any questions.  Thanks!

**Comment by tristil** [comment]
@rubysolo Okay, added an ELSE statement and nested case statements work now. Overall, `lib/dentaku/parser.rb` is getting pretty gnarly IMO. I played around with different refactorings to encapsulate the case parsing code but I didn't want to changes things too much without discussion.

**Comment by tristil** [comment]
Also I have no idea what's going on with Travis. It doesn't seem to be related to my changes https://travis-ci.org/rubysolo/dentaku/jobs/98008028

**Comment by tristil** [comment]
@rubysolo Is there anything I should do to get this merged? I will try looking into the Travis CI issues later tonight.

**Comment by rubysolo** [comment]
Merged this, thank you for contributing!  I made a slight change to keep 1.9 compatibility.  It looks like the travis issue was some rubygems / bundler bug -- updating to the newest versions fixes it.

**Comment by tristil** [comment]
Great! Thanks. I'll follow with some README updates when I get some time, maybe tonight.

**Pull request closed without merging**
