### PR TITLE
Adding a case sensitive mode to Dentaku::Calculator instance

### PR DESCRIPTION
**Pull request by jonhue**
Following up on #146

### CODE REVIEW

**Comment by jonhue** [comment]
The example in the README illustrates how it works.

**Comment by rubysolo** [comment]
nice, thanks!

**Comment by jonhue** [comment]
One more thing, do you think it would be possible to add support for multiple equations per key when evaluating bulk expressions without too much effort?

I'm taking about something like this:
```ruby
calc = Dentaku::Calculator.new
calc.store 'first': 1
calc.store 'equation': 2
equations = {}
equations['key'] = ['first * equation', 'second * equation']
calculator.solve equations
```

And if, where would be a good place to start?

**Comment by rubysolo** [comment]
This already works as of fb12788cca1e4a33f1a35300aa5ac920d11828ac.

```
calc = Dentaku::Calculator.new
calc.store 'first': 1
calc.store 'second': 2
calc.store 'equation': 3
equations = {}
equations['key'] = ['first * equation', 'second * equation']
calc.solve equations
#=> {"key"=>[3, 6]}
```

**Comment by jonhue** [comment]
@rubysolo But ...

```ruby
$ calc = Dentaku::Calculator.new
$ calc.store 'first': 1
$ calc.store 'equation': 3
$ equations = {}
$ equations['key'] = ['first * equation', 'second * equation']
$ calc.solve equations
=> {"key"=>:undefined}
```

... is this behavior intended?

**Comment by rubysolo** [comment]
I suppose it could return `{"key" => [3, :undefined]}` since we have enough context to evaluate the first expression.  Is that what you are expecting?

**Comment by jonhue** [comment]
@rubysolo Yes. I would either expect that or just `{"key" => 3}`.

**Comment by jonhue** [comment]
@rubysolo Do you still intend to change this behavior?

**Comment by rubysolo** [comment]
Yes, I think returning an array of values (or `:undefined` when we are missing dependencies) is the most consistent option.  When I find the time I will work on that, or feel free to send a PR if you want.

**Comment by jonhue** [comment]
@rubysolo I can try. I don't know where to start tho. My guess would be `BulkExpressionSolver`, but where do you return the calculated results?

**Comment by rubysolo** [comment]
Yes, that's right.  My guess is that `expression_dependencies` is returning a flat array of dependencies for an array of expressions, and I would probably approach this change by first changing that to return a 2d array there.

**Comment by rubysolo** [comment]
I'll take a look at this tonight.

**Comment by rubysolo** [comment]
This behavior is fixed in 2906c55b032f7785cee04a5426a5753cb11ef805

**Comment by jonhue** [comment]
@rubysolo Thank you so much :> It works beautifully!

**Comment by rubysolo** [comment]
👍 awesome!

**Pull request closed without merging**
