### PR TITLE
Allow string input numeric functions

### LINKED ISSUE #119: Numerify arguments for Ruby math functions
Great gem!

Yet, I ran into a small inconvenience.

Since the following works fine with String arguments:
```ruby
Dentaku('3 + x', x: '5') == 8
```

I also expected this to work:
```ruby
Dentaku('MAX(3, x)', x: '5') == 5
```

But instead I get a error telling me I can't compare Integers with Strings in the max function of Ruby. Within the Arthmetic functions the arguments are converted to numbers before evaluation but not in the other functions.

I would suggest to convert all arguments to Numeric for all functions where relevant. That would be MAX, MIN, ROUND, ROUNDDOWN, ROUNDUP and the Ruby Math functions.

In my fork I got MAX and MIN working with this principle, if you like I can submit a PR when I'm done with this.

### PR DESCRIPTION
**Pull request by nvanoorschot**
Closes #119 

The functions we discussed now accept Strings as input and convert them to Numeric. Where possible it converts is to Integer otherwise to BigDecimal, just as with the arithmetic functions.

I think you should also add a Coveralls badge to show the high level of testcoverage. I included the basic setup, but if you don't like it I'll take it out.

I look forward to your feedback.

### CODE REVIEW

**Comment by rubysolo** [comment]
Great, thanks!

**Comment by nvanoorschot** [comment]
I noticed that the Roundup and Ruby Math functions do not have their inputs cast to numeric on the master branch. It looks like commit "9d04932" did not get merged. Any idea on what went wrong?

**Comment by rubysolo** [comment]
Sorry, I'm not sure how that got dropped.  Should be good now.

**Comment by nvanoorschot** [comment]
No problem, looks good now!

**Pull request closed without merging**
