### PR TITLE
Add operator methods to comparator class

### PR DESCRIPTION
**Pull request by prashantvithani**

### CODE REVIEW

**Comment by rubysolo** [comment]
Thanks for contributing this!  Can you tell me a little about your use case?

**Comment by prashantvithani** [comment]
Well, I've been using AST (arithmetic expression) to build mongo aggregation query. Since the operators are defined for each arithmetic class, I can easily map them to corresponding aggregation operator.

Now I also want to use AST for conditional expression and I got to know that operators (symbols) are not defined for comparators. The absence of the `operator` method for comparators also gives the feeling of inconsistency as they are used in conditions similar to the arithmetic operators are used in expressions.

I have also made a change to the `type` method of `If` class. The main reason of this is, the dynamic value of `type` doesn't seem to be right. Keeping the value of `type` as `:condition` is more intuitive.

**Comment by rubysolo** [comment]
I think adding `operator` to the conditional nodes makes sense, but I'm not sure about changing the `type` of `IF`.  I was looking at `type` as describing the value that the node tree would produce if evaluated.  (As an example, the type of the `ROUND` function is `numeric`, because of what it will return)  I also made the assumption that for all uses of `IF(condition, A, B)` the types of the node trees A and B would be the same, so we can just return the type of tree A -- maybe that's not a good assumption though.

Can you explain more about how you're using `type` of `IF`?  Maybe we're missing a predicate method that is more about the AST node itself instead of the value that it will produce.

**Comment by prashantvithani** [comment]
I am using a recursive function iterating over AST tree of nodes to generate the mongo aggregation query. I need to identify whether current AST node represents arithmetic expression or conditional expression. The `type` of arithmetic AST is `numeric`, but I saw that the `type` of `IF` is not static but hardcoded to return the value of `A` (as per the example in above comment).

However, I didn't know that it reflects the type of return value, but I looked at it as the type of AST node. So, is there any way of distinguishing the arithmetic or conditional AST node?

**Comment by rubysolo** [comment]
I merged this, but I made the method `:node_type` for the `IF` function -- I think it's useful to introspect on both the type of the node and the type of the value that it will produce.

**Pull request closed without merging**
